// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwou29dFF6St2YJ5oz5_b-mzJcBPBopwk',
    appId: '1:558846954442:web:f2e14bdeeed932be469d33',
    messagingSenderId: '558846954442',
    projectId: 'let-us-roam',
    authDomain: 'let-us-roam.firebaseapp.com',
    storageBucket: 'let-us-roam.appspot.com',
    measurementId: 'G-25RFY3ENWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBp3fqpbWgEVBdi1eEKmJJbqD3T-OcHZ4',
    appId: '1:558846954442:android:9b1b2f7db338627d469d33',
    messagingSenderId: '558846954442',
    projectId: 'let-us-roam',
    storageBucket: 'let-us-roam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfUU8TPx4QrQu9QSHfSW6bEjPYhpJoiT8',
    appId: '1:558846954442:ios:319544a46fdc6130469d33',
    messagingSenderId: '558846954442',
    projectId: 'let-us-roam',
    storageBucket: 'let-us-roam.appspot.com',
    iosBundleId: 'com.example.letUsRoam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfUU8TPx4QrQu9QSHfSW6bEjPYhpJoiT8',
    appId: '1:558846954442:ios:319544a46fdc6130469d33',
    messagingSenderId: '558846954442',
    projectId: 'let-us-roam',
    storageBucket: 'let-us-roam.appspot.com',
    iosBundleId: 'com.example.letUsRoam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwou29dFF6St2YJ5oz5_b-mzJcBPBopwk',
    appId: '1:558846954442:web:7567ba9901631406469d33',
    messagingSenderId: '558846954442',
    projectId: 'let-us-roam',
    authDomain: 'let-us-roam.firebaseapp.com',
    storageBucket: 'let-us-roam.appspot.com',
    measurementId: 'G-F73MMCLD31',
  );

}